---
- name: Converge
  hosts: all
  vars:
    winlogbeat_version: 6.2.4
    winlogbeat_output_beats: true
    winlogbeat_beats_host:
      - "graylog.apps.buy4.io:5044"
  roles:
    - role: stone-payments.winlogbeat
